x-environment-variables: &common-env-vars
  POSTGRES_DB: letters
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password

services:
  app:
    image: anandsandilya/letters-management-api:0.1
    env_file:
      - .env.app.prod
    ports:
      - "8004:8000"
    environment:
      <<: *common-env-vars
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - letter-management-app-network
    restart: always

  db:
    image: postgres:16
    environment:
      <<: *common-env-vars
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - letter-management-app-network
    restart: always

volumes:
  postgres-data:

networks:
  letter-management-app-network:
