name: Build and deploy on ghcr

on:
  push:
    branches:
      - deno-godly

env:
  SERVICE_NAME: paiperless-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # - name: Deploy to Google Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v1
      #   with:
      #     service: ${{ env.SERVICE_NAME }}
      #     image: ghcr.io/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      #     credentials: ${{ secrets.GCP_SA_KEY }}
